name: Deploy to shinyapps.io
on:
  # Run on any push
  push:
  # Run manually via button in Actions menu
  workflow_dispatch:



jobs:


  deploy:
    name: Deploy to shinyapps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev


    
      - name: Deploy to shinyapps.io
        env:
          SHINY_TOKEN: ${{secrets.SHINYAPPTOKEN }}
          SHINY_SECRET: ${{ secrets.SHINYAPPSECRET }}
        run: |
          Rscript -e 'install.packages("rsconnect",repos="https://cran.rstudio.com")'
          Rscript -e 'install.packages("shiny",repos="https://cran.rstudio.com")'
          Rscript -e 'install.packages("shinydashboard",repos="https://cran.rstudio.com")'
          Rscript -e "library(rsconnect)"
          Rscript -e "rsconnect::setAccountInfo(name='pingliao', token=Sys.getenv('SHINY_TOKEN'), secret=Sys.getenv('SHINY_SECRET'))"
          Rscript -e "rsconnect::deployApp(appName='Quantify_Your_Degree', forceUpdate=TRUE)"
